name: Deploy to Github 
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to Github 
    runs-on: ubuntu-latest
    env:
      VITE_APP_NAME: "Hasil Karya"
      VITE_API_ENDPOINT: "https://api-system.hasilkarya.co.id/api/v1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install packages
        run: npm i
      - name: Set Creds
        run: |
          git config user.name "xrafffcode"
          git config user.email "yusfiwawan2@gmail.com"
      - name: Deploy
        run: npm run deploy
